general:
  iflowName: flow1
  iflowVersion: 1.0.1

steps:
  integrationArtifactDeploy:
    cpiCredentialsId: roverpocOauthCred
    integrationFlowId: smtp
    integrationFlowVersion: 2.0
    host: https://roverpoc.it-accd002.cfapps.sap.hana.ondemand.com
    oAuthTokenProviderUrl: https://roverpoc.authentication.sap.hana.ondemand.com/oauth/token
